# Generated by Django 4.2.20 on 2025-04-17 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_pics',
            field=models.ImageField(blank=True, null=True, upload_to='profilepics/'),
        ),
    ]
