# Generated by Django 4.2.20 on 2025-04-20 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0002_customuser_profile_pics'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_online',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
