# Generated by Django 5.1.5 on 2025-04-07 04:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thrift', '0002_remove_order_product_remove_product_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thrift.address'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('gopay', 'Gopay'), ('ovo', 'Ovo'), ('dana', 'Dana'), ('cod', 'Cash On Delivery'), ('credit', 'Credit/Card Bank'), ('bank', 'BCA'), ('va', 'Virtual Account')], max_length=20),
        ),
        migrations.AlterField(
            model_name='review',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
