# Generated by Django 4.2.20 on 2025-04-28 09:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thrift', '0003_collection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='phone_number',
            field=models.CharField(help_text='Format yang diterima: 081234567890, 6281234567890, atau +6281234567890', max_length=15, validators=[django.core.validators.RegexValidator(message='Masukkan nomor yang valid: contoh 081234567890 atau +6281234567890', regex='^(?:\\+62|62|0)8[1-9][0-9]{6,9}$')]),
        ),
    ]
